apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: homeworking
spec:
  selector:
    app: postgres-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432